LogisticRegression:
  penalty: ['l1', 'l2']
  C: [5, 2, 1, 0.1,0.05, 0.03, 0.0275,0.025, 0.02 , 0.01, 0.009, 0.0075, 0.005, 0.001]
  class_weight: ['balanced']
  random_state: [100,200, 300, 400]
  max_iter: [5, 10, 15, 20, 30, 50, 80, 100]
  fit_intercept: [True, False]
  tol: [0.1, 0.05 ,0.01, 0.001, 0.0001, 0.00001]
RandomForestClassifier:
  n_estimators: [5, 10, 20, 30, 50]
  max_features: [5, 10, 15, 20 , 30]
  criterion : ['gini', 'entropy']
  max_depth: [50, 100, 200, 500]
  random_state: [100]
  min_samples_split: [2, 3, 5]
SVM:
  classifier__C: [5, 2, 1, 0.1, 0.01, 0.001]
  classifier__kernel: ['rbf', 'linear']
  classifier__degree: [2, 3]
